export {
  frameToPptx,
  logicalToPptxX,
  logicalToPptxY,
  type PptxFrame,
  pptxToLogicalX,
  pptxToLogicalY,
} from "./coordinates.js";
export {
  ChartElementIRSchema,
  ConnectorElementIRSchema,
  DeckIRSchema,
  DiagnosticSchema,
  ElementIRSchema,
  FillIRSchema,
  FrameIRSchema,
  GroupElementIRSchema,
  IconElementIRSchema,
  ImageElementIRSchema,
  LineElementIRSchema,
  MasterIRSchema,
  ParagraphIRSchema,
  parseDeckIR,
  ResolvedThemeIRSchema,
  ShapeElementIRSchema,
  SlideIRSchema,
  SourceLocationSchema,
  StrokeIRSchema,
  safeParseDeckIR,
  TableElementIRSchema,
  TextElementIRSchema,
  TextRunIRSchema,
  TextStyleIRSchema,
} from "./schema.js";
export * from "./types.js";
