export {
  type ChartContractIssue,
  type ChartContractIssueCode,
  type ChartContractResult,
  validateChartContract,
} from "./chart-contract.js";
export {
  frameToPptx,
  logicalToPptxX,
  logicalToPptxY,
  type PptxFrame,
  pptxToLogicalX,
  pptxToLogicalY,
} from "./coordinates.js";
export {
  AudioElementIRSchema,
  BackgroundIRSchema,
  ChartElementIRSchema,
  ConnectorElementIRSchema,
  DeckIRSchema,
  DiagnosticSchema,
  ElementIRSchema,
  FillIRSchema,
  FrameIRSchema,
  GroupElementIRSchema,
  IconElementIRSchema,
  ImageElementIRSchema,
  LineElementIRSchema,
  MasterIRSchema,
  ParagraphIRSchema,
  parseDeckIR,
  ResolvedThemeIRSchema,
  ShapeElementIRSchema,
  SlideIRSchema,
  SourceLocationSchema,
  StrokeIRSchema,
  safeParseDeckIR,
  TableElementIRSchema,
  TextElementIRSchema,
  TextRunIRSchema,
  TextStyleIRSchema,
  VideoElementIRSchema,
} from "./schema.js";
export {
  MAX_TABLE_CELL_SPAN,
  MAX_TABLE_GRID_COLUMNS,
  scaleTableDimensions,
  TABLE_DIMENSION_EPSILON,
  type TableGridCellLike,
  type TableGridRowLike,
  type TableGridValidationIssue,
  type TableGridValidationIssueCode,
  type TableGridValidationResult,
  tableDimensionsMatch,
  tableDimensionTotal,
  validateTableGrid,
} from "./table-grid.js";
export * from "./types.js";
